name: publish
on:
  push:
    tags:
      - '*.*.*.*'
jobs:
  Build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Get Environment Variables
      run: |
        $tag = "${{ github.ref }}" -replace 'refs/tags/', ''

        "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV

    - name: Download Dalamud Latest
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Restore dependencies
      run: dotnet restore EasyZoomReborn.csproj

    - name: Build Plugin
      run: dotnet build --no-restore -c Release EasyZoomReborn.csproj -p:AssemblyVersion=${{ env.tag }} -p:FileVersion=${{ env.tag }} -p:InformationalVersion=${{ env.tag }} --output .\build

    - name: Zip Plugin
      run: Compress-Archive -Path .\build\* -DestinationPath .\build\EasyZoomReborn.zip

    - name: Publish Plugin
      uses: softprops/action-gh-release@v3
      with:
        files: ./build/EasyZoomReborn.zip
        token: ${{ secrets.GITHUB_TOKEN }}
